# Generated by Django 5.2.4 on 2025-07-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
